"""add project models

Revision ID: 037392cf5d17
Revises: 6f91b7161f16
Create Date: 2026-01-31 16:40:53.605208

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "037392cf5d17"
down_revision = "6f91b7161f16"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contributors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "category",
            sa.Enum("A", "B", "C", "D", "E", name="categoryenum"),
            nullable=True,
        ),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("department", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("group", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "facilities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("TESTING", "TRANSVERSE", name="facilitytypeenum"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_projects_code"), ["code"], unique=False)
        batch_op.create_index(batch_op.f("ix_projects_name"), ["name"], unique=False)

    op.create_table(
        "batches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("prefix", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("project_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("unit", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("identifier", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("referent_id", sa.Uuid(), nullable=True),
        sa.Column("technical_referent_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["referent_id"],
            ["contributors.id"],
        ),
        sa.ForeignKeyConstraint(
            ["technical_referent_id"],
            ["contributors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("batch_id", sa.Uuid(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("is_corporate", sa.Boolean(), nullable=False),
        sa.Column("is_confirmed", sa.Boolean(), nullable=False),
        sa.Column("finality", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "strategic_interests", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("synergies", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("risks", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("parades", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["batch_id"],
            ["batches.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "deliverables",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("contractual_end_date", sa.DateTime(), nullable=True),
        sa.Column("is_principal", sa.Boolean(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "activity_deliverables",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("deliverable_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["deliverable_id"],
            ["deliverables.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "annual_contributions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("contributor_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("days", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["contributor_id"],
            ["contributors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "annual_facility_usages",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.Column("facility_id", sa.Uuid(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("cost", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "purchases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("time_created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("time_updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("supplier", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("min_estimated_cost", sa.Float(), nullable=True),
        sa.Column("estimated_cost", sa.Float(), nullable=True),
        sa.Column("max_estimated_cost", sa.Float(), nullable=True),
        sa.Column("activity_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("purchases")
    op.drop_table("annual_facility_usages")
    op.drop_table("annual_contributions")
    op.drop_table("activity_deliverables")
    op.drop_table("deliverables")
    op.drop_table("activities")
    op.drop_table("customers")
    op.drop_table("batches")
    with op.batch_alter_table("projects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_projects_name"))
        batch_op.drop_index(batch_op.f("ix_projects_code"))

    op.drop_table("projects")
    op.drop_table("facilities")
    op.drop_table("contributors")
    # ### end Alembic commands ###
