"""add prefix to activity

Revision ID: 49776d34ff34
Revises: 6ca9208e4750
Create Date: 2026-02-03 20:46:18.028089

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes


from alembic import op

# revision identifiers, used by Alembic.
revision = '49776d34ff34'
down_revision = '6ca9208e4750'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('prefix')

    # ### end Alembic commands ###
