"""add year to purchase

Revision ID: 6ca9208e4750
Revises: ae1c4a96cf40
Create Date: 2026-02-03 01:16:30.569690

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes


from alembic import op

# revision identifiers, used by Alembic.
revision = '6ca9208e4750'
down_revision = 'ae1c4a96cf40'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=False))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_column('year')

    # ### end Alembic commands ###
