"""init models

Revision ID: 6f91b7161f16
Revises: 
Create Date: 2026-01-19 23:41:29.866589

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = '6f91b7161f16'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operation', postgresql.ENUM('READ', 'WRITE', 'DELETE', 'CREATE', 'SHARE', name='operation'), nullable=True),
    sa.Column('resource_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('who', postgresql.ENUM('user', 'admin', 'team', 'session', 'connected', 'anonymous', name='who'), nullable=True),
    sa.Column('who_id', sa.Uuid(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('acls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_acls_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_acls_who_id'), ['who_id'], unique=False)

    op.create_table('blacklist',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('time_until', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_key'), ['key'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversations_resource_id'), ['resource_id'], unique=False)

    op.create_table('folders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('for_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('for_id', sa.Uuid(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subject', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('body_html', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sender', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('recipients', postgresql.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forwarded_to', sa.UUID(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['forwarded_to'], ['sessions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_settings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('custom_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('arguments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('processor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processor_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started', sa.Boolean(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('ended', sa.Boolean(), nullable=False),
    sa.Column('failed', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('artifacts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_id')
    )
    op.create_table('translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('language_target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('translated_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('translator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('translation_context', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('pseudo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email_verification_token_expires', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_hashed', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reset_password_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reset_password_token_expires', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('draft', sa.Boolean(), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('time_published', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_articles_title'), ['title'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('public_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extension', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extension_client', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mime_client', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size_client', sa.Float(), nullable=True),
    sa.Column('unprocessable', sa.Boolean(), nullable=True),
    sa.Column('mime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('size', sa.Float(), nullable=True),
    sa.Column('storage_id', sa.Uuid(), nullable=False),
    sa.Column('storage_folder_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('in_storage', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('upload_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['storage_id'], ['storage_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('mail_id', sa.Uuid(), nullable=False),
    sa.Column('mail_settings_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mail_id'], ['mails.id'], ),
    sa.ForeignKeyConstraint(['mail_settings_id'], ['mail_settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relation_folders_blocks',
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('resource_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('folder_id', 'resource_kind', 'resource_id')
    )
    op.create_table('task_slots',
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('processor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('teams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('time_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teams_name'), ['name'], unique=False)

    op.create_table('relation_memberships',
    sa.Column('team_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('team_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relation_memberships')
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teams_name'))

    op.drop_table('teams')
    op.drop_table('task_slots')
    op.drop_table('relation_folders_blocks')
    op.drop_table('messages')
    op.drop_table('mail_attempts')
    op.drop_table('files')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_title'))
        batch_op.drop_index(batch_op.f('ix_articles_slug'))

    op.drop_table('articles')
    op.drop_table('users')
    op.drop_table('translations')
    op.drop_table('tasks')
    op.drop_table('storage_settings')
    op.drop_table('sessions')
    op.drop_table('notifications')
    op.drop_table('mails')
    op.drop_table('mail_templates')
    op.drop_table('mail_settings')
    op.drop_table('interactions')
    op.drop_table('folders')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_resource_id'))
        batch_op.drop_index(batch_op.f('ix_conversations_key'))

    op.drop_table('conversations')
    op.drop_table('blacklist')
    with op.batch_alter_table('acls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_acls_who_id'))
        batch_op.drop_index(batch_op.f('ix_acls_resource_id'))

    op.drop_table('acls')
    # ### end Alembic commands ###
