"""add activity updates

Revision ID: 8d82829df7b6
Revises: c3b9d53b1364
Create Date: 2026-04-01 17:55:06.848628

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d82829df7b6'
down_revision = 'c3b9d53b1364'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'config',
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=False,
                server_default=sa.text('\'{"updates": null}\'::jsonb'),
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_column('config')

    # ### end Alembic commands ###
