"""add change email

Revision ID: a89a2e37064d
Revises: e5e3fba6fc53
Create Date: 2026-04-13 14:30:44.723756

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes


from alembic import op

# revision identifiers, used by Alembic.
revision = 'a89a2e37064d'
down_revision = 'e5e3fba6fc53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending_email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('change_email_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('change_email_token_expires', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('change_email_token_expires')
        batch_op.drop_column('change_email_token')
        batch_op.drop_column('pending_email')

    # ### end Alembic commands ###
