"""add NNI to contributor

Revision ID: ae1c4a96cf40
Revises: ce5923c134f2
Create Date: 2026-02-01 15:59:17.894070

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes


from alembic import op

# revision identifiers, used by Alembic.
revision = 'ae1c4a96cf40'
down_revision = 'ce5923c134f2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contributors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('NNI', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contributors', schema=None) as batch_op:
        batch_op.drop_column('NNI')

    # ### end Alembic commands ###
