"""add hidden property to activity

Revision ID: c247005e4fd0
Revises: 8d82829df7b6
Create Date: 2026-04-01 21:31:14.085645

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c247005e4fd0"
down_revision = "8d82829df7b6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "hidden",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    with op.batch_alter_table("deliverables", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "hidden",
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("deliverables", schema=None) as batch_op:
        batch_op.drop_column("hidden")

    with op.batch_alter_table("activities", schema=None) as batch_op:
        batch_op.drop_column("hidden")

    # ### end Alembic commands ###
