"""add cascade deletion

Revision ID: c3b9d53b1364
Revises: 49776d34ff34
Create Date: 2026-02-05 14:44:44.279050

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c3b9d53b1364'
down_revision = '49776d34ff34'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('activities_batch_id_fkey'), type_='foreignkey')
        # Recreate FK with CASCADE using the same constraint name to avoid renaming
        batch_op.create_foreign_key(batch_op.f('activities_batch_id_fkey'), 'batches', ['batch_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('activity_deliverables', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('activity_deliverables_activity_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('activity_deliverables_deliverable_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('activity_deliverables_deliverable_id_fkey'), 'deliverables', ['deliverable_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('activity_deliverables_activity_id_fkey'), 'activities', ['activity_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('annual_contributions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('annual_contributions_contributor_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('annual_contributions_activity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('annual_contributions_activity_id_fkey'), 'activities', ['activity_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('annual_contributions_contributor_id_fkey'), 'contributors', ['contributor_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('annual_facility_usages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('annual_facility_usages_activity_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('annual_facility_usages_facility_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('annual_facility_usages_facility_id_fkey'), 'facilities', ['facility_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('annual_facility_usages_activity_id_fkey'), 'activities', ['activity_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('batches_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('batches_project_id_fkey'), 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('customers_referent_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('customers_technical_referent_id_fkey'), type_='foreignkey')
        batch_op.drop_column('technical_referent_id')
        batch_op.drop_column('referent_id')

    with op.batch_alter_table('deliverables', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('deliverables_customer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('deliverables_customer_id_fkey'), 'customers', ['customer_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('purchases_activity_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('purchases_activity_id_fkey'), 'activities', ['activity_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('purchases_activity_id_fkey'), 'activities', ['activity_id'], ['id'])

    with op.batch_alter_table('deliverables', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('deliverables_customer_id_fkey'), 'customers', ['customer_id'], ['id'])

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referent_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('technical_referent_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('customers_technical_referent_id_fkey'), 'contributors', ['technical_referent_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('customers_referent_id_fkey'), 'contributors', ['referent_id'], ['id'])

    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('batches_project_id_fkey'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('annual_facility_usages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('annual_facility_usages_facility_id_fkey'), 'facilities', ['facility_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('annual_facility_usages_activity_id_fkey'), 'activities', ['activity_id'], ['id'])

    with op.batch_alter_table('annual_contributions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('annual_contributions_activity_id_fkey'), 'activities', ['activity_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('annual_contributions_contributor_id_fkey'), 'contributors', ['contributor_id'], ['id'])

    with op.batch_alter_table('activity_deliverables', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('activity_deliverables_deliverable_id_fkey'), 'deliverables', ['deliverable_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('activity_deliverables_activity_id_fkey'), 'activities', ['activity_id'], ['id'])

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('activities_batch_id_fkey'), 'batches', ['batch_id'], ['id'])

    # ### end Alembic commands ###
