"""add names to customer

Revision ID: ce5923c134f2
Revises: 037392cf5d17
Create Date: 2026-01-31 21:10:09.881228

"""

import sqlalchemy as sa
import sqlmodel.sql.sqltypes


from alembic import op

# revision identifiers, used by Alembic.
revision = 'ce5923c134f2'
down_revision = '037392cf5d17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###
