"""add config to contributor

Revision ID: e5e3fba6fc53
Revises: c247005e4fd0
Create Date: 2026-04-01 21:51:43.655752

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "e5e3fba6fc53"
down_revision = "c247005e4fd0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contributors", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "config",
                postgresql.JSONB(astext_type=sa.Text()),
                nullable=False,
                server_default=sa.text("'{\"group_manager\": null}'::jsonb"),
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("contributors", schema=None) as batch_op:
        batch_op.drop_column("config")

    # ### end Alembic commands ###
