from ._base import (
    SklearnClassifier,
    SklearnMultiLabelClassifier,
    SklearnRegressor,
    SmartSklearnClassifier,
    SmartSklearnMultiLabelClassifier,
    _json_values,
    _text_values,
    _to_text,
    _vector_values,
)
from .fv import (
    GradientBoostingFeatureVectorRegressor,
    LassoFeatureVectorRegressor,
    LinearFeatureVectorRegressor,
    LogisticRegressionFeatureVectorClassifier,
    MLPFeatureVectorClassifier,
    PolynomialFeatureVectorRegressor,
    RandomForestFeatureVectorClassifier,
    RandomForestFeatureVectorRegressor,
    RidgeFeatureVectorRegressor,
    SklearnFeatureVectorClassifier,
    SklearnFeatureVectorRegressor,
    SmartLogisticRegressionFeatureVectorClassifier,
    SmartMLPFeatureVectorClassifier,
    SmartRandomForestFeatureVectorClassifier,
    SmartSVMFeatureVectorClassifier,
    SVMFeatureVectorClassifier,
    SVRFeatureVectorRegressor,
)
from .json import (
    GradientBoostingJsonClassifier,
    LinearSVMJsonClassifier,
    LogisticRegressionJsonClassifier,
    LogisticRegressionMultiLabelJsonClassifier,
    MLPJsonClassifier,
    MLPMultiLabelJsonClassifier,
    RandomForestJsonClassifier,
    RandomForestMultiLabelJsonClassifier,
    SGDJsonClassifier,
    SklearnJsonClassifier,
    SklearnJsonMultiLabelClassifier,
    SmartLogisticRegressionJsonClassifier,
    SmartLogisticRegressionMultiLabelJsonClassifier,
    SmartMLPJsonClassifier,
    SmartMLPMultiLabelJsonClassifier,
    SmartRandomForestJsonClassifier,
    SmartRandomForestMultiLabelJsonClassifier,
    SmartSklearnJsonClassifier,
    SmartSklearnJsonMultiLabelClassifier,
    SmartSVMJsonClassifier,
    SmartSVMMultiLabelJsonClassifier,
    SVMJsonClassifier,
    SVMMultiLabelJsonClassifier,
)
from .text import (
    AdaBoostTextClassifier,
    GradientBoostingTextClassifier,
    LogisticRegressionMultiLabelTextClassifier,
    LogisticRegressionTextClassifier,
    MLPMultiLabelTextClassifier,
    MLPTextClassifier,
    RandomForestMultiLabelTextClassifier,
    RandomForestTextClassifier,
    SklearnTextClassifier,
    SklearnTextMultiLabelClassifier,
    SmartAdaBoostTextClassifier,
    SmartGradientBoostingMultiLabelTextClassifier,
    SmartGradientBoostingTextClassifier,
    SmartLogisticRegressionMultiLabelTextClassifier,
    SmartLogisticRegressionTextClassifier,
    SmartMLPMultiLabelTextClassifier,
    SmartMLPTextClassifier,
    SmartRandomForestMultiLabelTextClassifier,
    SmartRandomForestTextClassifier,
    SmartSklearnTextClassifier,
    SmartSklearnTextMultiLabelClassifier,
    SmartSVMMultiLabelTextClassifier,
    SmartSVMTextClassifier,
    SVMMultiLabelTextClassifier,
    SVMTextClassifier,
)

__all__ = [
    # helpers
    "_to_text",
    "_text_values",
    "_json_values",
    "_vector_values",
    # abstract bases
    "SklearnClassifier",
    "SklearnMultiLabelClassifier",
    "SklearnRegressor",
    "SmartSklearnClassifier",
    "SmartSklearnMultiLabelClassifier",
    # text typed bases
    "SklearnTextClassifier",
    "SklearnTextMultiLabelClassifier",
    "SmartSklearnTextClassifier",
    "SmartSklearnTextMultiLabelClassifier",
    # text concrete single-label
    "SVMTextClassifier",
    "GradientBoostingTextClassifier",
    "RandomForestTextClassifier",
    "LogisticRegressionTextClassifier",
    "AdaBoostTextClassifier",
    "MLPTextClassifier",
    # text concrete multi-label
    "SVMMultiLabelTextClassifier",
    "RandomForestMultiLabelTextClassifier",
    "LogisticRegressionMultiLabelTextClassifier",
    "MLPMultiLabelTextClassifier",
    # text smart single-label
    "SmartSVMTextClassifier",
    "SmartLogisticRegressionTextClassifier",
    "SmartRandomForestTextClassifier",
    "SmartGradientBoostingTextClassifier",
    "SmartAdaBoostTextClassifier",
    "SmartMLPTextClassifier",
    # text smart multi-label
    "SmartSVMMultiLabelTextClassifier",
    "SmartRandomForestMultiLabelTextClassifier",
    "SmartLogisticRegressionMultiLabelTextClassifier",
    "SmartMLPMultiLabelTextClassifier",
    "SmartGradientBoostingMultiLabelTextClassifier",
    # json typed bases
    "SklearnJsonClassifier",
    "SklearnJsonMultiLabelClassifier",
    "SmartSklearnJsonClassifier",
    "SmartSklearnJsonMultiLabelClassifier",
    # json concrete single-label
    "SVMJsonClassifier",
    "LinearSVMJsonClassifier",
    "SGDJsonClassifier",
    "LogisticRegressionJsonClassifier",
    "RandomForestJsonClassifier",
    "MLPJsonClassifier",
    "GradientBoostingJsonClassifier",
    # json smart single-label
    "SmartSVMJsonClassifier",
    "SmartLogisticRegressionJsonClassifier",
    "SmartRandomForestJsonClassifier",
    "SmartMLPJsonClassifier",
    # json concrete multi-label
    "SVMMultiLabelJsonClassifier",
    "LogisticRegressionMultiLabelJsonClassifier",
    "MLPMultiLabelJsonClassifier",
    "RandomForestMultiLabelJsonClassifier",
    # json smart multi-label
    "SmartSVMMultiLabelJsonClassifier",
    "SmartLogisticRegressionMultiLabelJsonClassifier",
    "SmartRandomForestMultiLabelJsonClassifier",
    "SmartMLPMultiLabelJsonClassifier",
    # fv typed bases
    "SklearnFeatureVectorClassifier",
    "SklearnFeatureVectorRegressor",
    # fv concrete classifiers
    "SVMFeatureVectorClassifier",
    "LogisticRegressionFeatureVectorClassifier",
    "RandomForestFeatureVectorClassifier",
    "MLPFeatureVectorClassifier",
    # fv smart classifiers
    "SmartSVMFeatureVectorClassifier",
    "SmartLogisticRegressionFeatureVectorClassifier",
    "SmartRandomForestFeatureVectorClassifier",
    "SmartMLPFeatureVectorClassifier",
    # fv regressors
    "LinearFeatureVectorRegressor",
    "PolynomialFeatureVectorRegressor",
    "RidgeFeatureVectorRegressor",
    "LassoFeatureVectorRegressor",
    "RandomForestFeatureVectorRegressor",
    "GradientBoostingFeatureVectorRegressor",
    "SVRFeatureVectorRegressor",
]
